name: Security CI

on:
  push:
    branches: 
    - dev
  pull_request:
    branches:
    - main

  
jobs:
  security-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: GitLeaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: 'pip'
          cache-dependency-path: requirements-dev.txt
          
      - name: Bandit
        run: | 
          pip3 install -r requirements-dev.txt 
          bandit -r src/ -lll -f sarif  -o bandit-results.sarif
        
      - name: Upload Bandit SARIF to Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: bandit-results.sarif
          category: bandit

  build-and-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    needs: security-scan
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Docker Build
        run: docker build -t calculadora:${{ github.sha }} .

      - name: Trivy - SARIF para a aba Security
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: 'calculadora:${{ github.sha }}'
          scanners: 'vuln,secret,misconfig'
          format: 'sarif'
          output: 'trivy-results.sarif'
          ignore-unfixed: true
          severity: 'MEDIUM,HIGH,CRITICAL'
          limit-severities-for-sarif: true

      - name: Trivy - Upload SARIF to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: trivy-results.sarif
          category: trivy